create table "public"."user_organization" (
    "id" bigint generated by default as identity not null,
    "created_at" timestamp with time zone not null default now(),
    "user_id" integer,
    "organization_id" integer
);


alter table "public"."organizations" add column "is_personal" boolean;

alter table "public"."organizations" add column "slug" text;

CREATE UNIQUE INDEX user_organization_pkey ON public.user_organization USING btree (id);

alter table "public"."user_organization" add constraint "user_organization_pkey" PRIMARY KEY using index "user_organization_pkey";

alter table "public"."user_organization" add constraint "user_organization_organization_id_fkey" FOREIGN KEY (organization_id) REFERENCES organizations(id) ON DELETE CASCADE not valid;

alter table "public"."user_organization" validate constraint "user_organization_organization_id_fkey";

alter table "public"."user_organization" add constraint "user_organization_user_id_fkey" FOREIGN KEY (user_id) REFERENCES profiles(id) ON DELETE CASCADE not valid;

alter table "public"."user_organization" validate constraint "user_organization_user_id_fkey";