VALID_UNSTRUCTURED_DATA_TYPES = [
    "TXT",
    "PDF",
    "MARKDOWN",
    "GITHUB_REPOSITORY",
    "WEBPAGE",
    "NOTION",
    "URL",
]

VALID_STRUCTURED_DATA_TYPES = ["CSV", "AIRTABLE", "STRIPE"]
