VALID_UNSTRUCTURED_DATA_TYPES = [
    "TXT",
    "PDF",
    "DOCX",
    "PPTX",
    "MARKDOWN",
    "GITHUB_REPOSITORY",
    "WEBPAGE",
    "NOTION",
    "URL",
]

VALID_STRUCTURED_DATA_TYPES = ["AIRTABLE", "CSV", "STRIPE", "XLSX"]
