version: '3.8'

services:
  ai-firewall-node:
    build:
      context: ..
      dockerfile: docker/Dockerfile.node
    ports:
      - "8080:8080"
    environment:
      - NODE_ENV=production
      - PORT=8080
      # Traditional mode (set MULTITENANT=true to enable multitenant mode)
      - MULTITENANT=false
      # Multitenant environment variables (uncomment to enable)
      # - MULTITENANT=true
      # - MULTITENANT_CONFIG_API_URL=http://api:3000/api/proxy/
      # - REDIS_URL=redis://redis:6379
      # - CONFIG_CACHE_TTL=3600
      # - NINJA_LM_API_URL=http://redaction-api:3000/redact
    volumes:
      - ../superagent.yaml:/app/superagent.yaml:ro
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "node", "-e", "http.get('http://localhost:8080/health', (res) => { process.exit(res.statusCode === 200 ? 0 : 1) })"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    networks:
      - ai-firewall-network

  ai-firewall-rust:
    build:
      context: ..
      dockerfile: docker/Dockerfile.rust
    ports:
      - "8081:8080"
    environment:
      # Traditional mode (set MULTITENANT=true to enable multitenant mode)
      - MULTITENANT=false
      # Multitenant environment variables (uncomment to enable)
      # - MULTITENANT=true
      # - MULTITENANT_CONFIG_API_URL=http://api:3000/api/proxy/
      # - REDIS_URL=redis://redis:6379
      # - CONFIG_CACHE_TTL=3600
      # - NINJA_LM_API_URL=http://redaction-api:3000/redact
    volumes:
      - ../superagent.yaml:/app/superagent.yaml:ro
    restart: unless-stopped
    depends_on:
      - redis
    healthcheck:
      test: ["CMD", "./ai-firewall", "status"]
      interval: 30s
      timeout: 3s
      retries: 3
      start_period: 5s
    networks:
      - ai-firewall-network

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 30s
      timeout: 3s
      retries: 3
    networks:
      - ai-firewall-network

  redaction-api:
    build:
      context: ..
      dockerfile: docker/Dockerfile.api
    ports:
      - "3000:3000"
    environment:
      - PYTHONUNBUFFERED=1
      - HF_HOME=/app/models
    volumes:
      - api-models:/app/models
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    networks:
      - ai-firewall-network

volumes:
  api-models:
  redis-data:

networks:
  ai-firewall-network:
    driver: bridge