#!/bin/sh

echo "Checking and replacing NEXT_PUBLIC_ vars in .next with values from container environment"

replace_var() {
    VAR_NAME=$1
    PLACEHOLDER=$2
    if [ -z "${!VAR_NAME}" ]; then
        echo "Information: env var $VAR_NAME is not set so will not be replaced in .next public configuration"
    else
        find /app/.next \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i \
        -e "s#$PLACEHOLDER#${!VAR_NAME}#g"
        echo "Replaced $VAR_NAME with value: ${!VAR_NAME}"
    fi
}

replace_var "NEXT_PUBLIC_SUPERAGENT_API_URL" "APP_NEXT_PUBLIC_SUPERAGENT_API_URL"
replace_var "NEXT_PUBLIC_AWS_S3_BUCKET" "APP_NEXT_PUBLIC_AWS_S3_BUCKET"
replace_var "NEXT_PUBLIC_AWS_S3_REGION" "APP_NEXT_PUBLIC_AWS_S3_REGION"
replace_var "NEXT_PUBLIC_AMAZON_S3_ACCESS_KEY_ID" "APP_NEXT_PUBLIC_AMAZON_S3_ACCESS_KEY_ID"
replace_var "NEXT_PUBLIC_AMAZON_S3_SECRET_ACCESS_KEY" "APP_NEXT_PUBLIC_AMAZON_S3_SECRET_ACCESS_KEY"
replace_var "NEXT_PUBLIC_SHARABLE_KEY_SECRET" "APP_NEXT_PUBLIC_SHARABLE_KEY_SECRET"
replace_var "NEXT_PUBLIC_GITHUB_CLIENT_ID" "APP_NEXT_PUBLIC_GITHUB_CLIENT_ID"
replace_var "NEXT_PUBLIC_GITHUB_CLIENT_SECRET" "APP_NEXT_PUBLIC_GITHUB_CLIENT_SECRET"
replace_var "NEXT_PUBLIC_GOOGLE_CLIENT_ID" "APP_NEXT_PUBLIC_GOOGLE_CLIENT_ID"
replace_var "NEXT_PUBLIC_GOOGLE_CLIENT_SECRET" "APP_NEXT_PUBLIC_GOOGLE_CLIENT_SECRET"
replace_var "NEXT_PUBLIC_AZURE_AD_CLIENT_ID" "APP_NEXT_PUBLIC_AZURE_AD_CLIENT_ID"
replace_var "NEXT_PUBLIC_AZURE_AD_CLIENT_SECRET" "APP_NEXT_PUBLIC_AZURE_AD_CLIENT_SECRET"
replace_var "NEXT_PUBLIC_AZURE_AD_TENANT_ID" "APP_NEXT_PUBLIC_AZURE_AD_TENANT_ID"
replace_var "NEXT_PUBLIC_STRIPE_SECRET_KEY" "APP_NEXT_PUBLIC_STRIPE_SECRET_KEY"
replace_var "NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY" "APP_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
replace_var "NEXT_PUBLIC_SEGMENT_WRITE_KEY" "APP_NEXT_PUBLIC_SEGMENT_WRITE_KEY"
replace_var "NEXT_PUBLIC_STRIPE_FREE_PLAN_ID" "APP_NEXT_PUBLIC_STRIPE_FREE_PLAN_ID"
replace_var "NEXT_PUBLIC_PSYCHIC_PUBLIC_KEY" "APP_NEXT_PUBLIC_PSYCHIC_PUBLIC_KEY"
replace_var "NEXT_PUBLIC_AWS_OVERRIDE_S3_BASEURL" "APP_NEXT_PUBLIC_AWS_OVERRIDE_S3_BASEURL"

echo "Starting UI"
npm start
