#!/bin/sh

echo "Check that we have the NEXT_PUBLIC_ vars set"

test -n "$NEXT_PUBLIC_SUPERAGENT_API_URL"
test -n "$NEXT_PUBLIC_AWS_S3_BUCKET"
test -n "$NEXT_PUBLIC_AWS_S3_REGION"
test -n "$NEXT_PUBLIC_AMAZON_S3_ACCESS_KEY_ID"
test -n "$NEXT_PUBLIC_AMAZON_S3_SECRET_ACCESS_KEY"
test -n "$NEXT_PUBLIC_SHARABLE_KEY_SECRET"
test -n "$NEXT_PUBLIC_GITHUB_CLIENT_ID"
test -n "$NEXT_PUBLIC_GITHUB_CLIENT_SECRET"
test -n "$NEXT_PUBLIC_GOOGLE_CLIENT_ID"
test -n "$NEXT_PUBLIC_GOOGLE_CLIENT_SECRET"
test -n "$NEXT_PUBLIC_AZURE_AD_CLIENT_ID"
test -n "$NEXT_PUBLIC_AZURE_AD_CLIENT_SECRET"
test -n "$NEXT_PUBLIC_AZURE_AD_TENANT_ID"
test -n "$NEXT_PUBLIC_STRIPE_SECRET_KEY"
test -n "$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY"
test -n "$NEXT_PUBLIC_SEGMENT_WRITE_KEY"
test -n "$NEXT_PUBLIC_STRIPE_FREE_PLAN_ID"
test -n "$NEXT_PUBLIC_PSYCHIC_PUBLIC_KEY"

echo "Replacing NEXT_PUBLIC_ vars in .next with values from container environment"
find /app/.next \( -type d -name .git -prune \) -o -type f -print0 | xargs -0 sed -i -e "s#APP_NEXT_PUBLIC_SUPERAGENT_API_URL#$NEXT_PUBLIC_SUPERAGENT_API_URL#g" -e "s#APP_NEXT_PUBLIC_AWS_S3_BUCKET#$NEXT_PUBLIC_AWS_S3_BUCKET#g" -e "s#APP_NEXT_PUBLIC_AWS_S3_REGION#$NEXT_PUBLIC_AWS_S3_REGION#g" -e "s#APP_NEXT_PUBLIC_AMAZON_S3_ACCESS_KEY_ID#$NEXT_PUBLIC_AMAZON_S3_ACCESS_KEY_ID#g" -e "s#APP_NEXT_PUBLIC_AMAZON_S3_SECRET_ACCESS_KEY#$NEXT_PUBLIC_AMAZON_S3_SECRET_ACCESS_KEY#g" -e "s#APP_NEXT_PUBLIC_SHARABLE_KEY_SECRET#$NEXT_PUBLIC_SHARABLE_KEY_SECRET#g" -e "s#APP_NEXT_PUBLIC_GITHUB_CLIENT_ID#$NEXT_PUBLIC_GITHUB_CLIENT_ID#g" -e "s#APP_NEXT_PUBLIC_GITHUB_CLIENT_SECRET#$NEXT_PUBLIC_GITHUB_CLIENT_SECRET#g" -e "s#APP_NEXT_PUBLIC_GOOGLE_CLIENT_ID#$NEXT_PUBLIC_GOOGLE_CLIENT_ID#g" -e "s#APP_NEXT_PUBLIC_GOOGLE_CLIENT_SECRET#$NEXT_PUBLIC_GOOGLE_CLIENT_SECRET#g" -e "s#APP_NEXT_PUBLIC_AZURE_AD_CLIENT_ID#$NEXT_PUBLIC_AZURE_AD_CLIENT_ID#g" -e "s#APP_NEXT_PUBLIC_AZURE_AD_CLIENT_SECRET#$NEXT_PUBLIC_AZURE_AD_CLIENT_SECRET#g" -e "s#APP_NEXT_PUBLIC_AZURE_AD_TENANT_ID#$NEXT_PUBLIC_AZURE_AD_TENANT_ID#g" -e "s#APP_NEXT_PUBLIC_STRIPE_SECRET_KEY#$NEXT_PUBLIC_STRIPE_SECRET_KEY#g" -e "s#APP_NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY#$NEXT_PUBLIC_STRIPE_PUBLISHABLE_KEY#g" -e "s#APP_NEXT_PUBLIC_SEGMENT_WRITE_KEY#$NEXT_PUBLIC_SEGMENT_WRITE_KEY#g" -e "s#APP_NEXT_PUBLIC_STRIPE_FREE_PLAN_ID#$NEXT_PUBLIC_STRIPE_FREE_PLAN_ID#g" -e "s#APP_NEXT_PUBLIC_PSYCHIC_PUBLIC_KEY#$NEXT_PUBLIC_PSYCHIC_PUBLIC_KEY#g"

echo "Starting UI"
npm start
